version: '3'
services:
  flask:
    build: ./app
    image: 1kcdocker/flask
    restart: always
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
     - ./shared:/shared
  nginx:
    build: ./nginx
    image: 1kcdocker/nginx
    ports:
     - "80:80"
    volumes:
     - ./shared:/shared
     - ./html:/usr/share/nginx/html
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    expose:
     - "5432"
    volumes:
     - ./db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
     - "8080:8080"
