version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: app
      # POSTGRES_PASSWORD: docker
      POSTGRES_PASSWORD_FILE: /run/secrets/password
      POSTGRES_DB: app
    expose:
     - "5432"
    volumes:
     - ./db:/var/lib/postgresql/data
    secrets:
     - password   
  flask:
    build: ./app
    image: 1kcdocker/flask
    restart: always
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
     - ./shared:/shared
    secrets:
     - password   
    depends_on:
     - db
  nginx:
    build: ./nginx
    image: 1kcdocker/nginx
    ports:
     - "80:80"
    volumes:
     - ./shared:/shared
     - ./html:/usr/share/nginx/html
  adminer:
    image: adminer
    restart: always
    ports:
     - "8080:8080"
secrets:
  password:
    file: ./devsecrets/password
