version: '3'
services:
  flask:
    restart: always
    build: ./app
    image: 1kcdocker/flask
    ports:
     - "5000:5000"
    volumes:
     - ./app:/app
     - ./shared:/shared
  nginx:
    build: ./nginx
    image: 1kcdocker/nginx
    ports:
     - "80:80"
    volumes:
     - ./shared:/shared
     - ./html:/usr/share/nginx/html
