swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /sample:
    get:
      operationId: sample.read_all
      tags:
        - Sample
      summary: Read the entire set of samples, sorted by date
      description: Read the entire set of samples, sorted by date
      responses:
        200:
          description: Successfully read sample set operation
          schema:
            type: array
            items:
              properties:
                grain_id:
                  type: string
                  description: Id of the sample
                date:
                  type: string
                  description: Creation/Update timestamp of the sample
                l_value:
                  type: number
                  format: float
                  description: L value
                harmful:
                  type: boolean
                  description: Detected Harmful
                photo:
                  type: string
                  description: Link to photo
    post:
      operationId: sample.create
      tags:
        - Sample
      summary: Create a sample
      description: Create a new sample
      parameters:
        - name: sample
          in: body
          description: Sample to create
          required: True
          schema:
            type: object
            properties:
              l_value:
                type: number
                format: float
                description: L value
              harmful:
                type: boolean
                description: Detected Harmful
              photo:
                type: string
                description: Link to photo
      responses:
        201:
          description: Successfully created sample
          schema:
            properties:
              date:
                type: string
                description: Creation/Update timestamp of the sample
              l_value:
                type: number
                format: float
                description: L value
              harmful:
                type: boolean
                description: Detected Harmful
              photo:
                type: string
                description: Link to photo
              timestamp:
                type: string
                description: Creation/Update timestamp of the sample

